# Services
services:

  # Mosquitto
  mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
    networks:
      - my-network

# Volumes
volumes:
  mqtt:

# Networks
networks:
  my-network:
    driver: bridge
